### ISSUE TITLE
Question with Hashlink!

### ISSUE THREAD

**Issue by felixakiragreen** [starburst997/xcode-heaps#1]
Hi! Thank you for making this repo 🥇. I found it this thread: https://github.com/HaxeFoundation/hashlink/issues/144 and I've been talking to Justin Walsh on Heaps Gitter trying to get iOS up and running.

I understand that you're not supporting this so no obligation to help.

I'm stuck at this step: `haxe build-hlc.hxml`. I get this error:
`Code generated in submodules/hashlink/src/_main.c automatic native compilation not yet implemented`
But then I discovered that haxelib installed `hashlink@0.1.0` and it was using that one.

So I modified your `./install.sh` file from:
`haxelib install hashlink`
to:
`haxelib dev hashlink submodules/hashlink`

But now I get:
```sh
haxe build-hlc.hxml
Error: Error parsing haxelib.json for hashlink@dev: [file_contents,/Users/luke/dev/haxe/xcode-heaps/submodules/hashlink/haxelib.json]
Error: Build failed
```

I've tried moving `submodules/hashlink/other/haxelib/haxelib.json` to `submodules/hashlink/haxelib.json` but then I get: 
```sh
haxe build-hlc.hxml
Error: Library hashlink version dev does not have a run script
Error: Build failed
```

I tried `cmake .`, `make` inside `submodules/hashlink`, it builds but still get the same errors.

I'm not sure what I'm doing wrong, but I'm sure it's something pretty easy/minor that I've just missed or overlooked because I'm a noob. :(

(Also, I needed to install: `hscript`, & `hxbit`)

**Comment by starburst997** [comment]
Yo! So you do want to use `haxelib install hashlink`, the reason why it's not working using the "dev" one is because you're missing a `run.n` in that directory, alternatively you could compile it yourself, but it's just easier to use the official one on haxelib.

`Code generated in submodules/hashlink/src/_main.c automatic native compilation not yet implemented` means that the hlc code was compiled successfully.

You're right, completely forgot `hscript` and `hxbit`, and also having hashlink installed is a prerequisite (but is only a `make all && make install` away, in the hashlink directory).

I'll add those steps in `install.sh`.

Then, once hlc is compiled, open the XCode project `heaps-iOS.xcodeproj`, click `Build` and it should hopefully works, you'll probably have to tweak the "dev team" / "signing" option and the "Bundle Identifier".

<img width="721" alt="screen shot 2018-05-14 at 3 39 36 pm" src="https://user-images.githubusercontent.com/77518/40019374-0c1e1a10-578d-11e8-951f-f3ca30870413.png">

I do hope to get it all running eventually with a simple `./compile-everything-and-run-on-ios.sh`

**Comment by starburst997** [comment]
Let me know if you get it to run also, and feel free to send a PR. I tried to set this up using the latest on heaps / hashlink with as little modification as possible, it's still got some rough edges but it really isn't that far off. I'm trying to make a case to eventually try heaps where I work at for our next project.

**Comment by felixakiragreen** [comment]
@starburst997 I got it up and running! Thanks so much for your help. Yeah, for some reason I thought `automatic native compilation not yet implemented` was an error message and it didn't work.
